### ISSUE TITLE
安全牛百度网盘拉下来的解压密码错误

### ISSUE THREAD

**Issue by SilurianYang** [xuanhun/HackingResource#1]
##  我下载的是这个地址中的视频

[视频教程]kali linux 渗透测试全集

链接: https://pan.baidu.com/s/1RmcsE3OCHH-hpsQqStP-AA 提取码: vymm

## 目录下有附带解压密码，所有的尝试了一遍。依然密码错误

![QQ截图20210417172221](https://user-images.githubusercontent.com/31280665/115108180-99928700-9fa1-11eb-981e-67c72380542d.jpg)
![QQ截图20210417172241](https://user-images.githubusercontent.com/31280665/115108188-a0b99500-9fa1-11eb-964c-84f9953b3ea2.jpg)
![QQ截图20210417172253](https://user-images.githubusercontent.com/31280665/115108194-a3b48580-9fa1-11eb-91cb-b18ac8e92f82.jpg)

**Comment by SilurianYang** [comment]
## np  密码就是： 《【"'{[(《<www.176ku.com>》)]}'"】复制括号引号里的全部是解压密码。》

**Comment by null-sgq** [comment]
解压密码就是：《【"'{[(《<www.176ku.com>》)]}'"】复制括号引号里的全部是解压密码。》
这一段话。对的，有汉字
